- name: Variables
  hosts: localhost
  vars:
    WISH: "morning from vars"
  vars_file:
  -var.yaml
  tasks:
  - name: Intro with variables
    ansible.builtin.debug:
      msg: "This is {{Name}} ,having {{exp}} years of experinece"