- name: conditions
  hosts: web
  become: true
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expence
    ignore_errors: true
    register: USER
  
  - name: print user info
    ansible.builtin.debug:
     msg: "{{USER}}"
  
  - name: create user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0
     

  - name: say HEllo
    ansible.builtin.debug: 
      msg: "Hello"