- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: enter number
    private: false
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "{{number}} is less than 10"
    when: number < 10
  - name: number is greater than 10
    ansible.builtin.debug:
      msg: "{{number}} is greater than 10"
    when: number > 10 